# Generated by Django 3.1.5 on 2021-01-18 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='kind name')),
                ('alias', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='kind alias')),
                ('introdution', models.TextField(blank=True, null=True, verbose_name='introdution')),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='tag name')),
            ],
        ),
        migrations.CreateModel(
            name='MessageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('create_date', models.DateTimeField()),
                ('adjustment_date', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_m', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='BlogList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, unique=True, verbose_name='blog title')),
                ('blog_content', models.TextField(blank=True, null=True, verbose_name='blog content')),
                ('md_content', models.TextField(blank=True, null=True, verbose_name='markdown blog content')),
                ('graphic_url', models.CharField(blank=True, max_length=180, null=True, verbose_name='graphic url')),
                ('create_date', models.DateTimeField()),
                ('adjustment_date', models.DateTimeField(blank=True, null=True)),
                ('blog_kind', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog_backend.blogkind', verbose_name='blog kind select')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_b', to='users.user')),
                ('tag', models.ManyToManyField(to='blog_backend.Tag', verbose_name='tag select')),
            ],
        ),
    ]
