# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-06 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20190204_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='kind name')),
                ('alias', models.CharField(max_length=32, unique=True, verbose_name='kind alias')),
                ('introdution', models.TextField(verbose_name='introdution')),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180, null=True, verbose_name='blog title')),
                ('blog_content', models.TextField(blank=True, null=True, verbose_name='blog content')),
                ('md_content', models.TextField(blank=True, null=True, verbose_name='markdown blog content')),
                ('graphic_url', models.CharField(blank=True, max_length=180, null=True, verbose_name='graphic url')),
                ('create_date', models.DateTimeField()),
                ('adjustment_date', models.DateTimeField(blank=True, null=True)),
                ('blog_kind', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog_backend.BlogKind', verbose_name='blog kind select')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='kind name')),
            ],
        ),
        migrations.AddField(
            model_name='bloglist',
            name='tag',
            field=models.ManyToManyField(to='blog_backend.Tag', verbose_name='tag select'),
        ),
    ]
