# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0002_auto_20190208_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogkind',
            name='alias',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='kind alias'),
        ),
        migrations.AlterField(
            model_name='blogkind',
            name='introdution',
            field=models.TextField(blank=True, null=True, verbose_name='introdution'),
        ),
    ]
