# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-09 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0003_auto_20190209_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='tag name'),
        ),
    ]
