# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-09 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0004_auto_20190209_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='title',
            field=models.CharField(max_length=180, unique=True, verbose_name='blog title'),
        ),
    ]
