# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=128, unique=True)),
                ('introduce', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=128, verbose_name='\u5bc6\u7801')),
                ('email', models.EmailField(max_length=128, verbose_name='\u90ae\u7bb1')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u624b\u673a\u53f7')),
                ('head_pic_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u5934\u50cf')),
                ('person_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u59d3\u540d')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='\u51fa\u751f\u65e5\u671f')),
                ('card_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8eab\u4efd\u8bc1')),
                ('introduce', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u8bf4\u660e')),
                ('instaff_date', models.DateTimeField(auto_now=True, verbose_name='\u5165\u804c\u65e5\u671f')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_group', to='users.Group')),
            ],
        ),
    ]
