# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-31 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Another',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=20)),
                ('b', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=128, unique=True, verbose_name='groupname')),
                ('introduce', models.TextField(blank=True, max_length=200, null=True, verbose_name='introduce')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=128, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='phonenumber')),
                ('head_pic_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='headicon')),
                ('person_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='surname')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='birth')),
                ('card_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='identified card')),
                ('introduce', models.TextField(blank=True, max_length=200, null=True, verbose_name='introduce')),
                ('instaff_date', models.DateTimeField(auto_now=True, verbose_name='instaff date')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_group', to='users.Group')),
            ],
        ),
    ]
