# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-04 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_another'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.NullBooleanField(verbose_name='is_superadmin'),
        ),
    ]
