# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-04 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False, verbose_name='is_superadmin'),
        ),
    ]
