# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-15 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework_test', '0003_auto_20190215_0849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
